name: fitness_tracker
description: A local and web-compatible Fitness Tracker App built with Flutter and SQLite.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Animations
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  animations: ^2.0.8
  cupertino_icons: ^1.0.8

  # Local Storage & Database
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.8.3
  shared_preferences: ^2.3.2

  # Notifications (optional but supported in your setup)
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
